id: P007979
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG20958
  title: བོད་ཀྱི་གཏམ་དཔེ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    7136c86c14f54eb58bf91fb0a8adb5eb:
      image_group_id: I1KG20983
      title: Volume 1 of bod kyi gtam dpe phyogs bsgrigs/
      volume_number: 1
      total_pages: 142
      base_file: v001.txt
ebook_metadata:
  title: བོད་ཀྱི་གཏམ་དཔེ་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P007979
  cover: cover.jpg
  layers:
  - pagination
