id: P007979
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG20958
  title: བོད་ཀྱི་གཏམ་དཔེ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    72c4203de815476aa6141416489d8a02:
      image_group_id: I1KG20983
      title: ''
      volume_number: 1
      total_pages: 142
ebook_metadata:
  title: བོད་ཀྱི་གཏམ་དཔེ་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P007979
  cover: cover.jpg
  layers:
  - pagination
